// Code generated by goctl. DO NOT EDIT.
package types

type BaseResp struct {
	Code int    `json:"code"`
	Msg  string `json:"msg"`
}

type CaptchaReq struct {
}

type CaptchaResp struct {
	BaseResp
	Key  string `json:"key"`
	Data string `json:"data"` // base64编码的图片验证码
}

type CaptchaVerifyReq struct {
	Key  string `json:"key"`
	Code string `json:"code"`
}

type CaptchaVerifyResp struct {
	BaseResp
}

type EmailExistReq struct {
	Email string `json:"email"`
}

type EmailExistResp struct {
	BaseResp
}

type EmailSendReq struct {
	Email string `json:"email"`
}

type EmailSendResp struct {
	BaseResp
}

type LoginReq struct {
	Email    string `json:"email"`
	Type     int    `json:"type"`
	Password string `json:"password"`
	Key      string `json:"key"`
	Code     string `json:"code"`
}

type LoginResp struct {
	BaseResp
	Token Token        `json:"token"`
	User  UserBaseResp `json:"user"`
}

type RegisterReq struct {
	Email    string `json:"email"`
	Nickname string `json:"nickname"`
	Password string `json:"password"`
	Verify   string `json:"verify"`
}

type RegisterResp struct {
	BaseResp
	Token Token        `json:"token"`
	User  UserBaseResp `json:"user"`
}

type Token struct {
	AccessToken  string `json:"accessToken"`
	AccessExpire int64  `json:"accessExpire"`
	RefreshAfter int64  `json:"refreshAfter"`
}

type UserBaseResp struct {
	Id       int64  `json:"id"`
	Email    string `json:"email"`
	Nickname string `json:"nickname"`
	Avatar   string `json:"avatar"`
	OwnWords string `json:"ownWords"`
}

type UserInfoResp struct {
	UserBaseResp
}
